name: Deploy to Azure Container Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-to-acr:
    name: Build & Push to Azure Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: testdockerrk.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t mlprojects:latest .

      - name: Tag Docker Image for ACR
        run: |
          docker tag mlprojects:latest testdockerrk.azurecr.io/studentperformance:latest

      - name: Push Docker Image to ACR
        run: |
          docker push testdockerrk.azurecr.io/studentperformance:latest
